export const MockData = [
  {
    id: 1,
    name: "John",
    lastName: "Doe",
    region: "North America",
    igUsername: "john_doe",
    igFollowers: 256790,
    igReelPrice: 325,
    igPostPrice: 450,
    collabPrice: 275,
    tiktokFollowers: 785432,
    tiktokReelPrice: 210,
    tiktokUsername: "john_doe_tiktok",
    tiktokPostPrice: 375,
  },
  {
    id: 2,
    name: "Sarah",
    lastName: "Smith",
    region: "Europe",
    igUsername: "sarah_smith",
    igFollowers: 418759,
    igReelPrice: 180,
    igPostPrice: 320,
    collabPrice: 200,
    tiktokFollowers: 510237,
    tiktokReelPrice: 275,
    tiktokUsername: "sarah_smith_tiktok",
    tiktokPostPrice: 400,
  },
  {
    id: 3,
    name: "Michael",
    lastName: "Johnson",
    region: "North America",
    igUsername: "michael_johnson",
    igFollowers: 632148,
    igReelPrice: 405,
    igPostPrice: 495,
    collabPrice: 350,
    tiktokFollowers: 915802,
    tiktokReelPrice: 315,
    tiktokUsername: "michael_johnson_tiktok",
    tiktokPostPrice: 420,
  },
  {
    id: 4,
    name: "Emily",
    lastName: "Brown",
    region: "Europe",
    igUsername: "emily_brown",
    igFollowers: 327401,
    igReelPrice: 240,
    igPostPrice: 380,
    collabPrice: 275,
    tiktokFollowers: 126790,
    tiktokReelPrice: 190,
    tiktokUsername: "emily_brown_tiktok",
    tiktokPostPrice: 320,
  },
  {
    id: 5,
    name: "David",
    lastName: "Davis",
    region: "North America",
    igUsername: "david_davis",
    igFollowers: 482937,
    igReelPrice: 290,
    igPostPrice: 450,
    collabPrice: 300,
    tiktokFollowers: 672581,
    tiktokReelPrice: 195,
    tiktokUsername: "david_davis_tiktok",
    tiktokPostPrice: 380,
  },
  {
    id: 6,
    name: "Emma",
    lastName: "Wilson",
    region: "Europe",
    igUsername: "emma_wilson",
    igFollowers: 572931,
    igReelPrice: 360,
    igPostPrice: 475,
    collabPrice: 325,
    tiktokFollowers: 234879,
    tiktokReelPrice: 250,
    tiktokUsername: "emma_wilson_tiktok",
    tiktokPostPrice: 410,
  },
  {
    id: 7,
    name: "Christopher",
    lastName: "Anderson",
    region: "North America",
    igUsername: "christopher_anderson",
    igFollowers: 395827,
    igReelPrice: 275,
    igPostPrice: 425,
    collabPrice: 325,
    tiktokFollowers: 347592,
    tiktokReelPrice: 240,
    tiktokUsername: "christopher_anderson_tiktok",
    tiktokPostPrice: 400,
  },
  {
    id: 8,
    name: "Olivia",
    lastName: "Taylor",
    region: "Europe",
    igUsername: "olivia_taylor",
    igFollowers: 716429,
    igReelPrice: 420,
    igPostPrice: 500,
    collabPrice: 375,
    tiktokFollowers: 8234562,
    tiktokReelPrice: 285,
    tiktokUsername: "olivia_taylor_tiktok",
    tiktokPostPrice: 430,
  },
  {
    id: 9,
    name: "Daniel",
    lastName: "Thomas",
    region: "North America",
    igUsername: "daniel_thomas",
    igFollowers: 549378,
    igReelPrice: 315,
    igPostPrice: 475,
    collabPrice: 350,
    tiktokFollowers: 432175,
    tiktokReelPrice: 250,
    tiktokUsername: "daniel_thomas_tiktok",
    tiktokPostPrice: 410,
  },
  {
    id: 10,
    name: "Sophia",
    lastName: "Roberts",
    region: "Europe",
    igUsername: "sophia_roberts",
    igFollowers: 683245,
    igReelPrice: 390,
    igPostPrice: 490,
    collabPrice: 350,
    tiktokFollowers: 678943,
    tiktokReelPrice: 295,
    tiktokUsername: "sophia_roberts_tiktok",
    tiktokPostPrice: 420,
  },
];
